### ISSUE TITLE
npm run build FAILED

### ISSUE THREAD

**Issue by tecnolocoEdan** [mohebifar/racket#12]
When I run 'npm run build' , I get the next error.

C:\Projects\pruebas-react\racketApp\node_modules\.bin\webpack:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
                 ^^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3

**Comment by tecnolocoEdan** [comment]
Hello again, I got the workaround for this issue in #11
