### ISSUE TITLE
Exception running yo racket

### ISSUE THREAD

**Issue by mclouvem** [mohebifar/racket#8]
I've just installed yo and generator-racket and I got "Cannot find module 'yeoman-environment'" error after I ran the yo racket.

I'm running it in a linux machine, node version 6.2.2, NPM version 3.10.3

$ yo racket
module.js:442
    throw err;
    ^

Error: Cannot find module 'yeoman-environment'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/yo/lib/router.js:9:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

**Comment by mohebifar** [comment]
That's weird. I tried with those Node and NPM versions but I couldn't reproduce the error.

**Comment by sankhasp** [comment]
Could not reproduce this too. this should be closed

**Comment by AienTech** [comment]
@mclouvem please check your `yo` installation. this is an error related to yeoman:
https://github.com/yeoman/yeoman/issues/1569
